### ISSUE TITLE
Please verify if all the room making/viewing/peeking functions are working as intended

### ISSUE THREAD

**Issue by VineethRV** [VineethRV/timetablearchitect#33]
its hard for me to verify without UI

**Comment by VijeshVS** [comment]
use postman to verify it would be much easier. I have to go through lot of debugging if i write frontend logic without testing backend properly.

**Comment by VijeshVS** [comment]
@VineethRV i cannot test it until shreya completes the frontend code for it

**Comment by VineethRV** [comment]
okay, i will let her know
